### ISSUE TITLE
when is it going live ???

### ISSUE THREAD

**Issue by shimanyi** [ikosenn/ikosenn.me#1]

**Comment by ikosenn** [comment]
got a bit lazy. I’ll try have it up sometime next week

**Comment by shimanyi** [comment]
sawa sawa. I am following hehe

Regards,

## ​

​

*Shimanyi Valentino Osoro *
Developer - Sisitech Inc http://sisitech.com/.
25420 - 00603
KENYA.

|www.sisitech.com | www.c4dlab.ac.ke http://www.deveint.com/ |

**Comment by ikosenn** [comment]
haha… cool
